### ISSUE TITLE
Convert to number?

### ISSUE THREAD

**Issue by wormiedk** [mdeweerd/zha_custom#2]
I am using this to get the load from my danfoss ally thermostats. However when I read the values from the SQL database they come back as char values instead of int. Is there a way to tell your integration to do the conversion? I found that using it to update input_number helpers does the trick but is a bit backwards :)

**Comment by mdeweerd** [comment]
I'ld avoid accessing the SQL database directly unless really needed.

If you use 'attr_read' the read value can be set directly in a state.  The type should match the type of the zigbee attribute.

How attribute values are written to the database is not handled by this component but determined by zigpy/zha and definitions in the quirks.

I checked this overview of the attributes, but I am not sure what you mean by "load"  - I suppose that it's not the "load estimate".
https://raw.githubusercontent.com/SimpleUserHA/DanfosseTRV/main/Danfoss%20Ally%20Radiator%20Thermostat%201.08%20Zigbee%20Cluster%20Specifications%2016122020.pdf .

If you're targetting the heating demand, you can access the value like this.
```yaml
# sensors.yaml
- platform: template
  sensors:
    danfoss_etrv0100_f42ef0fe_pi_heating_percent:
      friendly_name: "DANFOSS Ouverture"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('climate.danfoss_etrv0100_f42ef0fe_thermostat','pi_heating_demand') }}"
```

```yaml
# In configuration.yaml
sensor: !include sensors.yaml
```
